apiVersion: mongodb.com/v1
kind: MongoDBSearch
metadata:
  name: mongodb-rs
  namespace: mongodb
spec:
  version: "8.2.1"
  source:
    mongodbResourceRef:
      name: mongodb-rs
  resourceRequirements:
    requests:
      cpu: "2"
      memory: "3Gi"
    limits:
      cpu: "3"
      memory: "5Gi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-rs-search-config
  namespace: mongodb
data:
  config.yml: |
    healthCheck:
      address: 0.0.0.0:8080
    logging:
      verbosity: INFO
    metrics:
      address: 0.0.0.0:9946
      enabled: true
    server:
      wireproto:
        address: 0.0.0.0:27027
        authentication:
          keyFile: /tmp/keyfile
          mode: keyfile
        tls:
          mode: Disabled
    storage:
      dataPath: /mongot/data
    syncSource:
      replicaSet:
        authSource: admin
        hostAndPort:
        - mongodb-rs-0.mongodb-rs-svc.mongodb.svc.cluster.local:27017
        - mongodb-rs-1.mongodb-rs-svc.mongodb.svc.cluster.local:27017
        - mongodb-rs-2.mongodb-rs-svc.mongodb.svc.cluster.local:27017
        passwordFile: /tmp/sourceUserPassword
        readPreference: secondaryPreferred
        tls: false
        username: search-sync-source
        authenticationMechanism: SCRAM-SHA-256
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-rs-search-sync-source-password
  namespace: mongodb
type: Opaque
stringData:
  password: "search-sync-password123"
---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: search-sync-source-user
  namespace: mongodb
spec:
  username: search-sync-source
  db: admin
  mongodbResourceRef:
    name: mongodb-rs
  passwordSecretKeyRef:
    name: mongodb-rs-search-sync-source-password
    key: password
  roles:
  - name: searchCoordinator
    db: admin
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-rs-search-svc
  namespace: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb-rs-search-svc
  ports:
  - port: 27027
    targetPort: 27027
    name: mongot
  - port: 8080
    targetPort: 8080
    name: health
  - port: 9946
    targetPort: 9946
    name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-search-external
  namespace: mongodb
spec:
  type: NodePort
  selector:
    app: mongodb-rs-search-svc
  ports:
  - port: 27027
    targetPort: 27027
    nodePort: 30003
