apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongodb-rs
  namespace: mongodb
spec:
  version: "8.2.1-ent"
  type: ReplicaSet
  members: 3
  credentials: ops-manager-credentials
  opsManager:
    configMapRef:
      name: ops-manager-config
  security:
    authentication:
      enabled: true
      modes: ["SCRAM"]
      ignoreUnknownUsers: true
  persistent: true
  podSpec:
    podTemplate:
      spec:
        containers:
        - name: mongodb-enterprise-database
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          readinessProbe:
            exec:
              command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
              - --quiet
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
              - --quiet
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-rs-svc
  namespace: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb-rs-svc
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-external
  namespace: mongodb
spec:
  type: NodePort
  selector:
    app: mongodb-rs-svc
  ports:
  - port: 27018
    targetPort: 27017
    nodePort: 30002
